package model;

public enum CommandType {
    FILE_REQUEST,
    FILE_MESSAGE,
    LIST_REQUEST,
    LIST_MESSAGE,
    DELETE_REQUEST,
    PATH_UP,
    PATH_RESPONSE,
    PATH_IN_REQUEST,
    AUTHORIZATION,
    REGISTRATION,
    AUTH_RESPONSE,
    SIMPLE_MESSAGE

}
